sudo: false
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - g++-6
      - clang-3.8
      - libusb-1.0-0-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libasio-dev
install:
  - "[ $CXX = g++ ] && export CXX=g++-6 && export CC=gcc-6 || true"
  - "[ $CXX = clang++ ] && export CXX=clang++-3.8 && export CC=clang-3.8 || true"
  - ./getasio.sh
script:
  - mkdir build && cd build && cmake .. && make
